#!/bin/bash

vcom 000-constants.vhd
vcom 01-iv.vhd
vcom 01-nd2.vhd
vcom a.b-datapath.core/b.b.a-nd3.vhd
vcom a.b-datapath.core/b.b.b-nd4.vhd
vcom 02-P4adder.core/a.a.a.a-fa.vhd
vcom 02-P4adder.core/a.a.a-rca.vhd
vcom 02-P4adder.core/a.a.b-mux21.vhd
vcom a.b-datapath.core/b.a.a-mux51.vhd
vcom 02-P4adder.core/a.a-carry_select_block.vhd
vcom 02-P4adder.core/a-sum_generator.vhd
vcom 02-P4adder.core/b.a-g.vhd
vcom 02-P4adder.core/b.b-pg.vhd
vcom 02-P4adder.core/b.c-pg_elem_net.vhd
vcom 02-P4adder.core/b-carry_generator.vhd
vcom 02-P4adder.vhd
vcom a.b-datapath.core/b.a.b-encoder.vhd
vcom a.b-datapath.core/b.a-boothmul.vhd
vcom a.b-datapath.core/b.d.c-counter.vhd
vcom a.b-datapath.core/b.d.b-left_shifter.vhd
vcom a.b-datapath.core/b.d.a-PIPO.vhd
vcom a.b-datapath.core/b.d-divider.vhd
vcom a.b-datapath.core/b.c-shifter.vhd
vcom a.b-datapath.core/b.b-logicals.vhd
vcom a.b-datapath.core/b.e-FSM_DECODE.vhd
vcom a.b-datapath.core/b-ALU.vhd
vcom a.b-datapath.core/c-BTB.vhd
vcom a.b-datapath.core/f-RS.vhd
vcom a.a-CU.vhd
vcom a.b-datapath.core/a-registerfile.vhd
vcom a.b-datapath.core/d-RAT.vhd
vcom a.b-datapath.core/g-ROB.vhd
vcom a.b-datapath.core/e-CAM.vhd
vcom a.b-datapath.vhd
vcom a-DLX.vhd
vcom b-IRAM.vhd
vcom test_bench/TB_dlx.vhd